const sequelize = require('./config/database');
const Ad = require('./models/Ad');

const seedDatabase = async () => {
  await sequelize.sync({ force: true }); 

  await Ad.bulkCreate([
    {
      title: 'Vulcanizare roți',
      description: 'Servicii de vulcanizare roți rapide și eficiente',
      county: 'București',
      locality: 'București',
      serviceType: 'Vulcanizare',
      carType: 'Autoturisme',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '08:00-20:00',
      rating: 5,
      provider:'vulcanizaretare@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Tractări auto',
      description: 'Servicii de tractări auto non-stop',
      county: 'Cluj',
      locality: 'Cluj-Napoca',
      serviceType: 'Tractări',
      carType: 'Autoturisme',
      isOnlineAppointment: false,
      is24_7: true,
      paymentMethods: 'Cash, Card',
      workingHours: 'Non-Stop',
      rating: 4.5,
      provider:'tractarinonstop@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Service Non-Stop',
      description: 'Reparații auto non-stop pentru toate tipurile de vehicule',
      county: 'Iași',
      locality: 'Iași',
      serviceType: 'Service',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: true,
      is24_7: true,
      paymentMethods: 'Cash, Card, Transfer Bancar',
      workingHours: 'Non-Stop',
      rating: 5,
      provider:'servicenonstop@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Diagnoză auto',
      description: 'Diagnoză computerizată pentru toate tipurile de vehicule',
      county: 'Timiș',
      locality: 'Timișoara',
      serviceType: 'Diagnoză',
      carType: 'Autoturisme',
      isOnlineAppointment: true,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '09:00-18:00',
      rating: 3.2,
      provider:'diagnoza@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Spălătorie auto',
      description: 'Spălătorie auto profesională',
      county: 'Constanța',
      locality: 'Constanța',
      serviceType: 'Spălătorie',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '08:00-20:00',
      rating: 4.7,
      provider:'spalatorie@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Tunning auto',
      description: 'Servicii de tuning auto pentru toate tipurile de vehicule',
      county: 'Brașov',
      locality: 'Brașov',
      serviceType: 'Tuning',
      carType: 'Autoturisme',
      isOnlineAppointment: true,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '10:00-19:00',
      rating: 5,
      provider:'tunning@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Vopsitorie auto',
      description: 'Servicii profesionale de vopsitorie auto',
      county: 'Argeș',
      locality: 'Pitești',
      serviceType: 'Vopsitorie',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card, Transfer Bancar',
      workingHours: '08:00-17:00',
      rating: 5,
      provider:'vopsitorie@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Întreținere și reparații',
      description: 'Servicii de întreținere și reparații pentru toate tipurile de vehicule',
      county: 'Bihor',
      locality: 'Oradea',
      serviceType: 'Întreținere',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: true,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '08:00-18:00',
      rating: 2.6,
      provider: 'reparatii@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Electrică auto',
      description: 'Servicii de electrică auto pentru toate tipurile de vehicule',
      county: 'Arad',
      locality: 'Arad',
      serviceType: 'Electrică',
      carType: 'Autoturisme',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '09:00-17:00',
      rating: 2.9,
      provider:'electrica@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Vulcanizare mobilă',
      description: 'Servicii de vulcanizare mobilă, la domiciliul clientului',
      county: 'Galați',
      locality: 'Galați',
      serviceType: 'Vulcanizare',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: true,
      is24_7: true,
      paymentMethods: 'Cash, Card',
      workingHours: 'Non-Stop',
      rating: 4.7,
      provider:'vulcanizaremobila@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Detailing interior/exterior',
      description: 'Servicii de detailing interior și exterior pentru toate tipurile de vehicule',
      county: 'Sibiu',
      locality: 'Sibiu',
      serviceType: 'Detailing',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: true,
      is24_7: false,
      paymentMethods: 'Cash, Card, Transfer Bancar',
      workingHours: '08:00-20:00',
      rating: 5,
      provider:'detailing@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Reparații cutii de viteze',
      description: 'Servicii profesionale de reparații cutii de viteze',
      county: 'Mureș',
      locality: 'Târgu Mureș',
      serviceType: 'Reparații',
      carType: 'Autoturisme',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '08:00-17:00',
      rating: 3.8,
      provider:'reparatiicutii@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Detailing interior/exterior',
      description: 'Servicii de detailing interior și exterior pentru toate tipurile de vehicule',
      county: 'Cluj',
      locality: 'Cluj-Napoca',
      serviceType: 'Detailing',
      carType: 'Autoturisme, Camioane',
      isOnlineAppointment: true,
      is24_7: false,
      paymentMethods: 'Cash, Card, Transfer Bancar',
      workingHours: '08:00-20:00',
      rating: 5,
      provider:'detailingcluj@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: 'Reparații cutii de viteze',
      description: 'Servicii profesionale de reparații cutii de viteze',
      county: 'Cluj',
      locality: 'Turda',
      serviceType: 'Reparații',
      carType: 'Autoturisme',
      isOnlineAppointment: false,
      is24_7: false,
      paymentMethods: 'Cash, Card',
      workingHours: '08:00-17:00',
      rating: 3.8,
      provider:'reparatiicutiicluj@yahoo.com',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {title: 'Vulcanizare roți rapide',
    description: 'Servicii rapide de vulcanizare roți',
    county: 'București',
    locality: 'București',
    serviceType: 'Vulcanizare',
    carType: 'Autoturisme',
    isOnlineAppointment: false,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-20:00',
    rating: 4.7,
    provider: 'vulcanizare@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Servicii electrice auto',
    description: 'Diagnoză și reparații electrice auto',
    county: 'Ilfov',
    locality: 'Voluntari',
    serviceType: 'Electronică',
    carType: 'Autoturisme',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '09:00-18:00',
    rating: 4.8,
    provider: 'electrica.auto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Tractări auto rapide',
    description: 'Servicii rapide de tractări auto',
    county: 'Cluj',
    locality: 'Cluj-Napoca',
    serviceType: 'Tractări',
    carType: 'Autoturisme',
    isOnlineAppointment: false,
    is24_7: true,
    paymentMethods: 'Cash, Card',
    workingHours: 'Non-Stop',
    rating: 4.9,
    provider: 'tractarirapid@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Vulcanizare mobilă 24/7',
    description: 'Vulcanizare mobilă la orice oră',
    county: 'Timiș',
    locality: 'Timișoara',
    serviceType: 'Vulcanizare mobilă',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: true,
    paymentMethods: 'Cash, Card',
    workingHours: 'Non-Stop',
    rating: 4.8,
    provider: 'vulcanizare.mobil@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Diagnoză auto computerizată',
    description: 'Diagnoză completă pentru autoturisme',
    county: 'Iași',
    locality: 'Iași',
    serviceType: 'Diagnoză',
    carType: 'Autoturisme',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '09:00-18:00',
    rating: 4.6,
    provider: 'diagnozaauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Service auto non-stop',
    description: 'Reparații auto disponibile non-stop',
    county: 'Brașov',
    locality: 'Brașov',
    serviceType: 'Service Non-Stop',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: true,
    paymentMethods: 'Cash, Card, Transfer Bancar',
    workingHours: 'Non-Stop',
    rating: 4.7,
    provider: 'servicenonstop@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Vulcanizare non-stop',
    description: 'Servicii de vulcanizare disponibile 24/7',
    county: 'Constanța',
    locality: 'Constanța',
    serviceType: 'Vulcanizare Non-Stop',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: true,
    paymentMethods: 'Cash, Card',
    workingHours: 'Non-Stop',
    rating: 4.8,
    provider: 'vulcanizarenonstop@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Închiriere autovehicule',
    description: 'Servicii de închiriere autovehicule pentru toate nevoile',
    county: 'Argeș',
    locality: 'Pitești',
    serviceType: 'Închiriere autovehicule',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-20:00',
    rating: 4.5,
    provider: 'inchiriereauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Linie I.T.P.',
    description: 'Inspecții tehnice periodice pentru autoturisme și camioane',
    county: 'Dolj',
    locality: 'Craiova',
    serviceType: 'Linie I.T.P.',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card, Transfer Bancar',
    workingHours: '08:00-17:00',
    rating: 4.6,
    provider: 'itp@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Thinichigerie auto',
    description: 'Servicii profesionale de thinichigerie auto',
    county: 'Bacău',
    locality: 'Bacău',
    serviceType: 'Thinichigerie',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-17:00',
    rating: 4.7,
    provider: 'thinichigerie@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Vopsitorie auto',
    description: 'Vopsitorie auto profesională pentru orice vehicul',
    county: 'Sibiu',
    locality: 'Sibiu',
    serviceType: 'Vopsitorie',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card, Transfer Bancar',
    workingHours: '08:00-18:00',
    rating: 4.8,
    provider: 'vopsitorieauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Colantare vehicule',
    description: 'Servicii de colantare auto personalizată',
    county: 'Buzău',
    locality: 'Buzău',
    serviceType: 'Colantare',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '09:00-18:00',
    rating: 4.9,
    provider: 'colantare@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Detailing interior auto',
    description: 'Servicii complete de detailing interior auto',
    county: 'Vâlcea',
    locality: 'Râmnicu Vâlcea',
    serviceType: 'Detailing interior',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-20:00',
    rating: 4.8,
    provider: 'detailinginterior@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Detailing exterior auto',
    description: 'Servicii profesionale de detailing exterior auto',
    county: 'Galați',
    locality: 'Galați',
    serviceType: 'Detailing exterior',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-20:00',
    rating: 4.7,
    provider: 'detailingexterior@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Spălătorie auto completă',
    description: 'Spălătorie auto completă, interior și exterior',
    county: 'Neamț',
    locality: 'Piatra Neamț',
    serviceType: 'Spălătorie auto',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: false,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-20:00',
    rating: 4.9,
    provider: 'spalatorieauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Tunning auto profesional',
    description: 'Servicii de tuning auto pentru performanțe maxime',
    county: 'Bihor',
    locality: 'Oradea',
    serviceType: 'Tunning Auto',
    carType: 'Autoturisme',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '10:00-19:00',
    rating: 5.0,
    provider: 'tunningauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Dezmembrări auto',
    description: 'Servicii de dezmembrări și piese auto',
    county: 'Arad',
    locality: 'Arad',
    serviceType: 'Dezmembrări',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: false,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '08:00-17:00',
    rating: 4.4,
    provider: 'dezmembrariauto@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Reparații parbrize',
    description: 'Servicii rapide de reparații și înlocuire parbrize',
    county: 'Suceava',
    locality: 'Suceava',
    serviceType: 'Parbrize',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: false,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '09:00-18:00',
    rating: 4.5,
    provider: 'reparatiiparbrize@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Diagnoză auto completă',
    description: 'Servicii de diagnoză completă pentru toate tipurile de vehicule',
    county: 'Bistrița-Năsăud',
    locality: 'Bistrița',
    serviceType: 'Diagnoză',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: false,
    paymentMethods: 'Cash, Card',
    workingHours: '09:00-18:00',
    rating: 4.6,
    provider: 'diagnozacompleta@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Tractări auto',
    description: 'Tractări auto disponibile 24/7',
    county: 'Maramureș',
    locality: 'Baia Mare',
    serviceType: 'Tractări',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: false,
    is24_7: true,
    paymentMethods: 'Cash, Card',
    workingHours: 'Non-Stop',
    rating: 4.7,
    provider: 'tractarimar@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Service Non-Stop',
    description: 'Reparații auto non-stop pentru toate tipurile de vehicule',
    county: 'Mehedinți',
    locality: 'Drobeta-Turnu Severin',
    serviceType: 'Service Non-Stop',
    carType: 'Autoturisme, Camioane',
    isOnlineAppointment: true,
    is24_7: true,
    paymentMethods: 'Cash, Card, Transfer Bancar',
    workingHours: 'Non-Stop',
    rating: 4.9,
    provider: 'servicenonstop@yahoo.com',
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

  console.log('Data has been seeded');
  process.exit();
};

seedDatabase();
